# Generated by Django 6.0 on 2025-12-04 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_instruction_remove_message_user_and_more'),
        ('medicines', '0001_add_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.CharField(blank=True, default='Терапевт', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='IssuedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_medicines', to='chat.profile')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_records', to='medicines.medicine')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
