# Generated by Django 6.0 on 2025-12-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mnn', models.CharField(max_length=255)),
                ('form', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('min_stock', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stock_per_pack', models.IntegerField()),
                ('diff', models.IntegerField()),
                ('article', models.CharField(max_length=20, unique=True)),
                ('qr_payload', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
